# Generated by Django 3.2.4 on 2021-06-22 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_producto_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
